export const categories = [
    {id: "Field 41", name: "3D Printing" },
    {id: "Field 42", name: "AdTech"},
    {id: "Field 43", name: "AgTech"},
    {id: "Field 44", name: "Analytics"},
    {id: "Field 45", name: "AI / ML / NLP / Computer Vision"},
    {id: "Field 46", name: "Audio"},
    {id: "Field 47", name: "Augmented & Virtual Reality / AR/ VR"},
    {id: "Field 48", name: "Automation"},
    {id: "Field 49", name: "Automotive / Autonomous Cars Mobility"},
    {id: "Field 50", name: "Beauty / Fashion"},
    {id: "Field 51", name: "Big Data"},
    {id: "Field 52", name: "Biotech"},
    {id: "Field 53", name: "Blockchain"},
    {id: "Field 54", name: "Cannabis"},
    {id: "Field 55", name: "Cleantech"},
    {id: "Field 56", name: "Cloud Infrastructure"},
    {id: "Field 57", name: "Construction Technology / Proptech / Built World / Real Estate"},
    {id: "Field 58", name: "Collaboration / Future of Work"},
    {id: "Field 59", name: "CPG / D2C / Consumer Brands / Consumer Products"},
    {id: "Field 60", name: "Cryptocurrencies"},
    {id: "Field 61", name: "Cybersecurity"},
    {id: "Field 62", name: "Data Services"},
    {id: "Field 63", name: "Dating"},
    {id: "Field 64", name: "Developer Tools"},
    {id: "Field 65", name: "Deep Tech"},
    {id: "Field 66", name: "Digital Health / Fitness / Wellness"},
    {id: "Field 67", name: "Digital Storage"},
    {id: "Field 68", name: "Distributed Workforce / Remote Workforce / Freelance"},
    {id: "Field 69", name: "E-commerce"},
    {id: "Field 70", name: "EdTech"},
    {id: "Field 71", name: "Energy"},
    {id: "Field 72", name: "Entertainment"},
    {id: "Field 73", name: "Environmental"},
    {id: "Field 74", name: "FemTech / Woman-led"},
    {id: "Field 75", name: "FinTech"},
    {id: "Field 76", name: "FoodTech"},
    {id: "Field 77", name: "FrontierTech"},
    {id: "Field 78", name: "Gaming / Games / Esports"},
    {id: "Field 79", name: "Govtech / Defense / Security / Regtech"},
    {id: "Field 80", name: "Hardware / HaaS / Hardware-enabled SaaS / Smart Hardware / Connected Hardware"},
    {id: "Field 81", name: "Hospitality"},
    {id: "Field 82", name: "HR"},
    {id: "Field 83", name: "Impact / Social Impact / Net Impact"},
    {id: "Field 84", name: "Industrial / Legacy / Old-World"},
    {id: "Field 85", name: "Information Technology"},
    {id: "Field 86", name: "InsurTech / Insurance"},
    {id: "Field 87", name: "IoT"},
    {id: "Field 88", name: "Legal"},
    {id: "Field 89", name: "Life Sciences / Pharma"},
    {id: "Field 90", name: "Location-based services"},
    {id: "Field 91", name: "Logistics / Transportation"},
    {id: "Field 92", name: "Manufacturing"},
    {id: "Field 93", name: "Marketing / Martech"},
    {id: "Field 94", name: "Marketplace / Platform"},
    {id: "Field 95", name: "Materials Science"},
    {id: "Field 96", name: "Med Devices"},
    {id: "Field 97", name: "Media / Content"},
    {id: "Field 98", name: "Messaging"},
    {id: "Field 99", name: "Metals & Mining / Natural Resources"},
    {id: "Field 100", name: "Metered Service"},
    {id: "Field 101", name: "Minority-Led"},
    {id: "Field 102", name: "Mobile"},
    {id: "Field 103", name: "Mortgage"},
    {id: "Field 104", name: "Nanotechnology"},
    {id: "Field 105", name: "Network Infrastructure"},
    {id: "Field 106", name: "Oil & Gas"},
    {id: "Field 107", name: "Open Source"},
    {id: "Field 108", name: "P2P / Peer to Peer"},
    {id: "Field 109", name: "Payments"},
    {id: "Field 110", name: "Pet Technology"},
    {id: "Field 111", name: "Physical Storage"},
    {id: "Field 112", name: "Publishing"},
    {id: "Field 113", name: "Restaurant"},
    {id: "Field 114", name: "Retail"},
    {id: "Field 115", name: "Ridesharing"},
    {id: "Field 116", name: "Robotics & Drones"},
    {id: "Field 117", name: "SaaS"},
    {id: "Field 118", name: "Sales & CRM"},
    {id: "Field 119", name: "Search"},
    {id: "Field 120", name: "SMB"},
    {id: "Field 121", name: "Social"},
    {id: "Field 122", name: "Software"},
    {id: "Field 123", name: "Space"},
    {id: "Field 124", name: "Travel"},
    {id: "Field 125", name: "UGC / User Generated Content"},
    {id: "Field 126", name: "Wearables"},
];

export default categories;